language: python

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y python-lxml python-pip
install:
 # here we don't use the travis default virtualenv because that
 # causes us to install lxml again below, doubling the build time
 # when it compiles the native modules from source
 - deactivate
 - gem install kramdown-rfc2629
 - sudo pip install xml2rfc

script: make ghpages

env:
  global:
    - secure: H/63OC4PX7+WIn6xlUnBVV5/JExIBUWkHJv3LKSuNcmmHdKbs+hmZLQyuUp6sWKSR4IelKrTs7rw4TO2Mq/aNKW2I4WSrFujCiVAxuE6f9RSii5U3IxbnCn8aFs3o3yd9PWPKmnq1jfi0wB+TD+SskrAM5IjplGcn0FdjK2C5y8=
